/* 
 * File: conditions_proximity.h
 * Author: martin
 *
 * Created on April 920158:46 PM
 */

//Conditions - proximity

//LIDAR scanner
CONDITION_MACRO(FRONT_LEFT_FAR_PROXIMITY, "Front.Left.Far.Prox")
CONDITION_MACRO(FRONT_CENTER_FAR_PROXIMITY, "Front.Center.Far.Prox")
CONDITION_MACRO(FRONT_RIGHT_FAR_PROXIMITY, "Front.Right.Far.Prox")
CONDITION_MACRO(LEFT_FAR_PROXIMITY, "Left.Far.Prox")
CONDITION_MACRO(REAR_LEFT_FAR_PROXIMITY, "Rear.Left.Far.Prox")
CONDITION_MACRO(REAR_CENTER_FAR_PROXIMITY, "Rear.Center.Far.Prox")
CONDITION_MACRO(REAR_RIGHT_FAR_PROXIMITY, "Rear.Right.Far.Prox")
CONDITION_MACRO(RIGHT_FAR_PROXIMITY, "Right.Far.Prox")

CONDITION_MACRO(FRONT_LEFT_PROXIMITY, "Front.Left.Prox")
CONDITION_MACRO(FRONT_CENTER_PROXIMITY, "Front.Center.Prox")
CONDITION_MACRO(FRONT_RIGHT_PROXIMITY, "Front.Right.Prox")
CONDITION_MACRO(LEFT_PROXIMITY, "Left.Prox")
CONDITION_MACRO(RIGHT_PROXIMITY, "Right.Prox")
CONDITION_MACRO(REAR_LEFT_PROXIMITY, "Rear.Left.Prox")
CONDITION_MACRO(REAR_CENTER_PROXIMITY, "Rear.Center.Prox")
CONDITION_MACRO(REAR_RIGHT_PROXIMITY, "Rear.Right.Prox")


